env:
  matrix:
    - EMACS=emacs-snapshot

before_install:
  - git submodule --quiet update --init --recursive

install:
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs-snapshot &&
        sudo apt-get -qq install emacs-snapshot-el;
    fi

script:
  - emacs --version
  - echo "Attempting initial startup..."
  - emacs -nw --batch \
          --eval '(let ((debug-on-error t)
                        (user-emacs-directory default-directory)
                        (user-init-file (expand-file-name "init.el"))
                        (load-path (delq default-directory load-path)))
                    (load-file user-init-file)
                    (run-hooks (quote after-init-hook))
                    (mk-compile-init-files))'
  - echo "Initial startup successful"
  - echo "Attempting secondary startup..."
  - time emacs -nw --batch \
          --eval '(let ((debug-on-error t)
                        (user-emacs-directory default-directory)
                        (user-init-file (expand-file-name "init.el"))
                        (load-path (delq default-directory load-path)))
                    (load-file user-init-file)
                    (run-hooks (quote after-init-hook)))'
  - echo "Secondary startup successful"

notifications:
  email: false
